# Generated by Django 3.2.9 on 2021-12-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heyurl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.URLField(),
        ),
    ]
